workflows:
  ios-build:
    name: iOS Simulator Build Only
    environment:
      vars:
        FLUTTER_VERSION: 3.38.5
        XCODE_VERSION: 26.1
        # 强制设置为模拟器构建
        FLUTTER_TARGET_PLATFORM: ios-simulator
        CODESIGNING_ALLOWED: NO
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Clean environment
        script: |
          # 安全清理环境，忽略不存在的文件
          rm -rf build/ || true
          rm -rf ios/.symlinks/ || true
          rm -rf ios/Pods/ || true
          rm -f ios/Podfile.lock || true
          echo "✅ 环境清理完成"

      - name: Set up Flutter
        script: |
          flutter --version
          flutter doctor -v
          # 预热Flutter
          flutter precache --ios

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Fix iOS Podfile
        script: |
          cd ios
          # 创建一个简化的Podfile，避免问题依赖
          cat > Podfile << 'EOF'
          platform :ios, '15.0'

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
            end
          end
          EOF

          echo "✅ Podfile创建完成"

      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update

      - name: Force Simulator Build
        script: |
          # 设置环境变量强制模拟器构建
          export FLUTTER_TARGET_PLATFORM=ios-simulator
          export CODESIGNING_ALLOWED=NO

          # 构建模拟器版本，明确指定设备
          flutter clean
          flutter pub get

          # 使用xcodebuild直接构建模拟器版本
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            build

          # 如果xcodebuild失败，尝试Flutter方法
          if [ $? -ne 0 ]; then
            echo "Flutter fallback method..."
            flutter build ios --simulator --release --no-codesign
          fi

      - name: Verify build
        script: |
          # 验证构建产物
          ls -la build/ios/iphonesimulator/ || ls -la build/ios/
          find . -name "*.app" -type d

    artifacts:
      - build/ios/**/Runner.app
      - build/ios/Build/Products/Release-iphonesimulator/*.app
