# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network requests when determining platform versions
# This can lead to errors in some network environments.
# Uncomment the following line to disable CocoaPods analytics.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 初始空的target - Flutter会在运行时添加插件
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 模拟器构建不需要代码签名
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''

      # 优化构建设置
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'

      # 修复架构问题
      config.build_settings['VALID_ARCHS'] = 'x86_64 arm64'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

      # 禁用一些警告
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end
