# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network requests when determining platform versions
# This can lead to errors in some network environments.
# Uncomment the following line to disable CocoaPods analytics.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# 集成Flutter插件
def flutter_root
  defined_xcode_path = nil
  if File.exist?(File.expand_path('../../.flutter-plugins', __FILE__))
    File.foreach(File.expand_path('../../.flutter-plugins', __FILE__)) do |line|
      plugin = line.split(' ')[0]
      path = plugin.split('=')[1]
      if path.include?('/flutter/')
        defined_xcode_path = File.expand_path(path + '/packages/flutter_tools/bin/xcode_backend.sh', __FILE__)
        break
      end
    end
  end
  defined_xcode_path ||= File.expand_path(File.join(File.dirname(__FILE__), '../../flutter/packages/flutter_tools/bin/xcode_backend.sh'))
  File.exist?(defined_xcode_path) ? File.expand_path(File.join(File.dirname(defined_xcode_path), '..')) : nil
end

# 检查Flutter是否可用并加载插件helper
require File.join(flutter_root, 'lib', 'flutter', 'podhelper.rb') if flutter_root

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 自动安装Flutter插件
  begin
    if flutter_root
      install_all_flutter_pods File.dirname(File.realpath(__FILE__))
    else
      # 如果flutter helper不可用，手动声明插件
      # 这些是基于pubspec.yaml中的依赖
      pod 'flutter_vpn'
      pod 'permission_handler'
      pod 'flutter_secure_storage'
    end
  rescue => e
    puts "Flutter插件安装失败: #{e}"
    puts "尝试手动安装插件..."
    # 备用手动安装
    pod 'flutter_vpn'
    pod 'permission_handler'
    pod 'flutter_secure_storage'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 模拟器构建不需要代码签名
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''

      # 优化构建设置
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'

      # 修复架构问题
      config.build_settings['VALID_ARCHS'] = 'x86_64 arm64'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'

      # 禁用一些警告
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end
